/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Grupo Oca (https://sketchfab.com/grupooca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mesa-de-jantar-code-augusta-doimo-agave-casa-207b8d89a9d34c2cb1e6f1219850c5c4
Title: MESA DE JANTAR CODE AUGUSTA DOIMO AGAVE CASA
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_18.geometry} material={materials.VIDRO} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.EdgeColo} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.BASE} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.EdgeColo} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.TAMPO} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
