/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Grupo Oca (https://sketchfab.com/grupooca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mesa-de-centro-quadrada-air-drio-agave-casa-3ebbad6d94384b3cb83720551898d401
Title: MESA DE CENTRO QUADRADA AIR DRIO AGAVE CASA
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials.Transluc} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.ESTRUTUR} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.PALHA} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
